global:
  scrape_interval: 5s

rule_files:
  - "prometheus_alerts.yml"
  - "slo_alerts.yml"

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "backend"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:4000"]
